version: '3.8'

services:

  redis:
    image: redis
    ports:
      - 6379:6379

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
