version: '3.8'

services:

  redis:
    image: redis
    container_name: redis
    command: sh -c "redis-server --appendonly yes && redis-cli flushall"
    volumes:
      - redis_data:/data
    restart: always
    # ports:
    #   - "6379:6379"

  load-balancer:
    # image: haproxy:2.4
    image: haproxy
    ports:
      - "4000:4000"
    volumes:
      # - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    depends_on:
      - server1
      - server2

  server1:
    build: .
    container_name: server1
    # ports:
    #   - "4001:4000"
    environment:
      APP_ID: 1000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TCP_HOST: '0.0.0.0'
      TCP_PORT: 4000

  server2:
    build: .
    container_name: server2
    # ports:
    #   - "4002:4000"
    environment:
      APP_ID: 1001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TCP_HOST: '0.0.0.0'
      TCP_PORT: 4000

volumes:
  redis_data:

  # client1:
  #   build: .
  #   container_name: client1
  #   command: ["node", "client.js"]
  #   environment:
  #     SERVER_HOST: server1
  #     SERVER_PORT: 3000
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379

  # client2:
  #   build: .
  #   container_name: client2
  #   command: ["node", "client.js"]
  #   environment:
  #     SERVER_HOST: server2
  #     SERVER_PORT: 3000
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
